### ISSUE TITLE
Tickets sendo fechados.

### ISSUE THREAD

**Issue by Disapper** [canove/whaticket-community#481]
Pessoal, não sei se ocorreu algum erro na instalação mais aqui comigo sempre quando está a algum tempo sem interação no ticket/conversa, o whaticket está fechando os ticket/conversa como resolvido.

Há como desabilitar essa feature?

**Comment by Kouthk** [comment]
![image](https://user-images.githubusercontent.com/34557801/199091965-7fbb214b-8f8e-4216-8037-af06a9422aa8.png)
Vai nesse arquivo ai e deixa a linha 
"REACT_APP_HOURS_CLOSE_TICKETS_AUTO =" 
isso define o tempo em que o ticket pode ficar sem interação alguma até que seja fechado automaticamente. =) 
Se deixar null,  os tickets nao irão se encerrar automaticamente

**Comment by codsec** [comment]
> ![image](https://user-images.githubusercontent.com/34557801/199091965-7fbb214b-8f8e-4216-8037-af06a9422aa8.png) Vai nesse arquivo ai e deixa a linha "REACT_APP_HOURS_CLOSE_TICKETS_AUTO =" isso define o tempo em que o ticket pode ficar sem interação alguma até que seja fechado automaticamente. =) Se deixar null, os tickets nao irão se encerrar automaticamente

é possivel setar minutos em vez de horas?

**Comment by Creapardesenvolvimento** [comment]
Ola será que é possível em minutos ?
