### ISSUE TITLE
Quem estiver com o problema: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')

### ISSUE THREAD

**Issue by eduamaral23** [canove/whaticket-community#486]
Altere a linha 17 no /backend/node_modules/whatsapp-web.js/src/util/Injected.js 
de: window.Store.GroupMetadata = window.mR.findModule((module) => module.default && module.default.handlePendingInvite)[0].default;

para:  window.Store.GroupMetadata = window.mR.findModule('GroupMetadata')[0].default.GroupMetadata

Isso resolve o problema, caso alguem queira ver o link eh esse : https://github.com/pedroslopez/whatsapp-web.js/issues/1786

**Comment by CSFelix** [comment]
It worked, thank you!
