### ISSUE TITLE
Erro de dependencias front-end, npm não instala

### ISSUE THREAD

**Issue by Guiviniac** [canove/whaticket-community#490]
# npm resolution error report

While resolving: frontend@0.1.0
Found: react@15.3.0
node_modules/react
  react@"15.3.0" from the root project

Could not resolve dependency:
peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4
node_modules/@material-ui/core
  @material-ui/core@"^4.11.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

npm não instala no front-end, sofre com algum erros de dependencia, alguém sabe como eu posso corrigir?

**Comment by jhonnatanBezerra** [comment]
deleta a pasta **node-modules**
deleta os arquivo **package-lock** e **yarn.lock** (se existir)
roda novamente o comando **npm install** ou **yarn** para instalar os pacotes novamente
