### ISSUE TITLE
Solução do problema Error: Evaluation failed: TypeError: msg.quotedMsgObj is not a function

### ISSUE THREAD

**Issue by eduamaral23** [canove/whaticket-community#494]
Pessoal, que estiver com o problema: Error: Evaluation failed: TypeError: msg.quotedMsgObj is not a function
Vá em /whatsapp-web.js/src/structures/Message.js 
Linha: 309
E altere 
de: return msg.quotedMsgObj().serialize(); 
para: return msg.getRawQuotedMsgObj().serialize()
Que resolve o problema.

**Comment by CJRMedeiros123** [comment]
Funcionou para mim!

**Comment by eduamaral23** [comment]
Os problemas foram resolvidos atualizando a ultima versão do whatsapp-web.js para 1.18.4, para os 2 whatsapp.
