### ISSUE TITLE
Arquivos faltando

### ISSUE THREAD

**Issue by AugustoGCP** [canove/whaticket-community#495]
Estou seguindo os passos do REAME.md, porém ao executar alguns comandos, não são encontrados arquivos ou vários erros por falta justamente de arquivos no clone.

Analisei o .gitignore os arquivos foram ignorados.

E necessário realizar aquisição e este repositório seria somente uma demonstração?

**Comment by emanuelbernardes** [comment]
Oi Augusto, infelizmente as vezes acontece isso mesmo... No meu git tem um repositório com um auto-installer se quiser...

**Comment by dollyzn** [comment]
Boa tarde! Os arquivos que você diz faltar são os `.env` do back e frontend? Caso sim, eles são baixados como `.env.example` e você teria de definir as variáveis e remover a extensão *.example* do arquivo
