### ISSUE TITLE
Session gets stuck and shows connected/connecting

### ISSUE THREAD

**Issue by mohaaosman** [canove/whaticket-community#498]
After a few days, the WhatsApp instance stops responding sometimes it's stuck on "connecting" or "connected" without any response.
The only ways you can enable it is to delete and add again or restart the server.

Is there a way I can monitor the instance and watch if the variable is still in the session array, that way I can restart it without deleting or restarting the app?

**Comment by eduamaral23** [comment]
If the device, where whatsapp is installed, is not online within 72 hours whatsapp, and the web becomes online, it disconnects automatically.
What I do here is restart every day via cron
Or you can also use npm restart.
