### ISSUE TITLE
[nginx] erro - sudo nginx -t !!AJUDA NA INSTALACAO!!

### ISSUE THREAD

**Issue by ewerton91** [canove/whaticket-community#499]
Estou com um erro na hora de executar o comando "sudo nginx -t" na instalação
Ja tentei remover o "/" adicionar e remover o "}" mudar o proxy, adicionar e remover o "......", porem sempre aparece um erro diferente. A configuracao abaixo foi o mais proximo de funcionar!

sempre aparece o erro=
_nginx: [emerg] invalid number of arguments in "location" directive in /etc/nginx/sites-enabled/whaticket-frontend:4
nginx: configuration file /etc/nginx/nginx.conf test failed_

meu whaticket-backend=
_server {
  server_name api.whatsnetwork.shop;_

  _location / {
    proxy_pass http://127.0.0.1:8080;
    }
}_

**Comment by eduamaral23** [comment]
Bom Dia... 
Eu acho.... que tu não esta passando todos os parametros..
Faltaram:
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_cache_bypass $http_upgrade;
