### ISSUE TITLE
No login, No add new user allowed

### ISSUE THREAD

**Issue by jbastos62** [canove/whaticket-community#500]
Hello,  i'been installing during the last two weeks and its imposible to connect..  Thanks in advance for your help.
![frontend](https://user-images.githubusercontent.com/83244061/207171740-913597c4-6087-41ba-9124-fb9cafce368c.png)
![running](https://user-images.githubusercontent.com/83244061/207171744-d419af0d-9723-484d-a456-c3db41bb4f07.png)

**Comment by eduamaral23** [comment]
Try install react-devtools:
npm install -g react-devtools

**Comment by jbastos62** [comment]
> Try install react-devtools: npm install -g react-devtools

Thanks , every thing its working fine now.
