### ISSUE TITLE
help me , Unsuccessful CORS request

### ISSUE THREAD

**Issue by Danielrr11** [canove/whaticket-community#504]
Cross-origin request blocked: The same origin policy does not allow reading remote resources at http://localhost:8080/socket.io/?EIO=4&transport=polling&t=OMeBjUh. (Reason: Unsuccessful CORS request.) Status code: (null).

does not start a session from another computer to the installation computer: 3000

**Comment by acarhuas** [comment]
Actualiza whatsapp-web.js

**Comment by alternativa2216** [comment]
Estou com o mesmo problema, já atualizei o que eu podia mais não consigo sair desse erro

**Comment by Danielrr11** [comment]
ya lo resolví


BACKEND_URL=http://colocar ip
FRONTEND_URL=https://colocar ipt:3000


y en la bd lo deje así

DB_HOST= localhost

y en el frontend 

REACT_APP_BACKEND_URL = http:// colocar ip:8080

**Comment by alternativa2216** [comment]
infelizmente no meu não funcionou

**Comment by Danielrr11** [comment]
cuando ingrese no colocar http://localhost:3000

colocar http://IP:3000

**Comment by alternativa2216** [comment]
mesmo assim não funcionou, acabei tendo o mesmo erro

**Comment by codsec** [comment]
Msm coisa cmg
