### ISSUE TITLE
Error when creating a new session

### ISSUE THREAD

**Issue by alex9044** [canove/whaticket-community#505]
Error when creating a new session, after adding a new whatsapp it shows loading, but the QR code button does not appear. This has happened since the server was restarted.
Anyone else had the same problem?

**Comment by eduamaral23** [comment]
Verify folder /whaticket/backend/.wwebjs_auth

**Comment by andrerds** [comment]
I am having the same issue, after the server restart I am no longer able to connect.

**Comment by andrerds** [comment]
> I am having the same issue, after the server restart I am no longer able to connect.

- Updated the package to the latest version "whatsapp-web.js": "^1.19.2"
- Changed in package.json to version 1.19.2.
- Ran command npm install
- Ran command npm run build
- Restarted pm2
- Done, it started working again.
