### ISSUE TITLE
Help app crashed

### ISSUE THREAD

**Issue by codsec** [canove/whaticket-community#512]
![image](https://user-images.githubusercontent.com/44205014/218113246-2f273a0d-e63a-4c89-8e12-887469a2d23a.png)

Fiz todos os passos da instalação direitinho(instalação local + docker), funcionou bem quando fiz um teste ontem no meu celular, mas agora estou tentando usar o qr code em outro smartphone e não está funcionando, simplesmente não reconhece, e tambem agora toda vez que dou npm start, ele começa a crashar... alguem sabe o que pode ser feito?

**Comment by jhonnatanBezerra** [comment]
Fizeram atualizações do Whatsapp.
Segue a correção:

Acessar o arquivo:
**node_modules/whatsapp-web.js/src/util/Injected.js**

alterar a linha que contem as informações:
`window.Store.QueryExist = window.mR.findModule('queryExists')[0].queryExists;`

para:

`window.Store.QueryExist = window.mR.findModule('queryExists')[0] ? window.mR.findModule('queryExists')[0].queryExists : window.mR.findModule('queryExist')[0].queryWidExists;`

depois só restartar o backend com o pm2:  `**pm2 restart idDobackend**` _(geralmente é 0)_

**Comment by codsec** [comment]
> Fizeram atualizações do Whatsapp. Segue a correção:
> 
> Acessar o arquivo: **node_modules/whatsapp-web.js/src/util/Injected.js**
> 
> alterar a linha que contem as informações: `window.Store.QueryExist = window.mR.findModule('queryExists')[0].queryExists;`
> 
> para:
> 
> `window.Store.QueryExist = window.mR.findModule('queryExists')[0] ? window.mR.findModule('queryExists')[0].queryExists : window.mR.findModule('queryExist')[0].queryWidExists;`
> 
> depois só restartar o backend com o pm2: `**pm2 restart idDobackend**` _(geralmente é 0)_

Muito obrigado salvou minha vida <3

**Comment by Luskan777** [comment]
Talvez a melhor solução seria atualizar  o modulo **whatsapp-web.js**.
Os desenvolvedores do  modulo  lançaram essa correção com  a versão mais recente, a [1.19.4](https://github.com/pedroslopez/whatsapp-web.js/releases/tag/v1.19.4).

pode só rodar o comando: 
`npm i whatsapp-web.js@1.19.4`
e depois reiniciar o serviço com: 
`pm2 restart $NOME_DO_SERVIÇO_BACKEND`

Obs: Todos os comandos devem ser executados no diretório do backend

**Comment by codsec** [comment]
> Talvez a melhor solução seria atualizar o modulo **whatsapp-web.js**. Os desenvolvedores do modulo lançaram essa correção com a versão mais recente, a [1.19.4](https://github.com/pedroslopez/whatsapp-web.js/releases/tag/v1.19.4).
> 
> pode só rodar o comando: `npm i whatsapp-web.js@1.19.4` e depois reiniciar o serviço com: `pm2 restart $NOME_DO_SERVIÇO_BACKEND`
> 
> Obs: Todos os comandos devem ser executados no diretório do backend

Vlw pelo help, mas estou tendo problemas com a aplicação travando do nada, sabe como eu poderia arrumar isso... quando o travamento ocorre isso aq aparece no console do navegador;
![image](https://user-images.githubusercontent.com/44205014/219146326-cd667fe6-df80-4088-9ecc-c03a1a5bc417.png)

**Comment by Luskan777** [comment]
> > Talvez a melhor solução seria atualizar o modulo **whatsapp-web.js**. Os desenvolvedores do modulo lançaram essa correção com a versão mais recente, a [1.19.4](https://github.com/pedroslopez/whatsapp-web.js/releases/tag/v1.19.4).
> > pode só rodar o comando: `npm i whatsapp-web.js@1.19.4` e depois reiniciar o serviço com: `pm2 restart $NOME_DO_SERVIÇO_BACKEND`
> > Obs: Todos os comandos devem ser executados no diretório do backend
> 
> Vlw pelo help, mas estou tendo problemas com a aplicação travando do nada, sabe como eu poderia arrumar isso... quando o travamento ocorre isso aq aparece no console do navegador; ![image](https://user-images.githubusercontent.com/44205014/219146326-cd667fe6-df80-4088-9ecc-c03a1a5bc417.png)

Você esta preenchendo a variável FRONTEND_URL ?

**Comment by codsec** [comment]
> Você esta preenchendo a variável FRONTEND_URL corretamente?

Meus .env estão assim

![image](https://user-images.githubusercontent.com/44205014/219151446-11326e0e-a419-4ee9-b074-547e6ffa2508.png)
![image](https://user-images.githubusercontent.com/44205014/219151517-fbc6f8c7-f1f9-46f1-9da7-828dbddced06.png)

**Comment by codsec** [comment]
> > Você esta preenchendo a variável FRONTEND_URL corretamente?
> 
> Meus .env estão assim
> 
> ![image](https://user-images.githubusercontent.com/44205014/219151446-11326e0e-a419-4ee9-b074-547e6ffa2508.png) ![image](https://user-images.githubusercontent.com/44205014/219151517-fbc6f8c7-f1f9-46f1-9da7-828dbddced06.png)

obs: estou utilizando o press-ticket uma versão mais atualizada do whaticket community, mas o erro q estou falando ocorre em ambos
