### ISSUE TITLE
Cors 

### ISSUE THREAD

**Issue by JJtarazona** [canove/whaticket-community#539]
Hola, ya he instalado whaticket, pero la momento de hacer registro o ingresar no me deja, cuando voy a ver los errores me arroja los siguiente por consola:  "Acess to XMLHttpRequest at 'http://localhost:8080/socket.io/?EIO=4&transport=polling&t=OUhMhK9' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://localhost:3000' that is not equal to the supplied origin." Alguien sabe como puedo solucionar?

**Comment by nicoforlano** [comment]
@JJtarazona Inicialmente había tenido el mismo error. 

En mi caso, al estar corriendo la aplicación en localhost, el problema era que la URL del frontend estaba definida usando https en envés de http. Por lo tanto, el backend no reconocía el origen e indicaba error de CORS.

Simplemente puedes cambiar la variable de entorno a FRONTEND_URL=http://localhost:3000 (en el archivo .env en /backend ) y correr nuevamente el backend.

**Comment by herbertamaro2** [comment]
Olá grupo!!
Estou com um problema aqui fiz a instalação no ubuntu aqui backend frontend.. Mais quando vou rodar o frontend em localhost:3000 fica travado com 'erro de CORS'

obs: Quando logo via postman funciona de boa o backend.
Já fiz de tudo aqui troquei as urls dos .envs umas dez mil vezes, estou 2 dias travado nesse CORS aee

#env frontend
REACT_APP_BACKEND_URL = http://localhost:8080/


#env backend
NODE_ENV=
BACKEND_URL=http://localhost
FRONTEND_URL=http://localhost:3000
PROXY_PORT=8080
PORT=8080

DB_HOST=localhost
DB_DIALECT=mysql
DB_USER=root
DB_PASS=
DB_NAME=whaticket

JWT_SECRET=3123123213123
JWT_REFRESH_SECRET=75756756756
