### ISSUE TITLE
duvidas sobre a documentação da api online

### ISSUE THREAD

**Issue by PwccaCode** [canove/whaticket-community#542]
sei que é possivel chamar a api online pra enviar uma mensagem pelo whatticket usando o token ali nas settings pra autenticar
queria saber aonde é possivel encontrar a documentação dos comandos aceitos por essa api

**Comment by MharkozBezerra** [comment]
Acredito que terá mais êxito, olhando o source da apiRouter, disponível na pasta `backend\src\routes`:
|- backend
|-----------\src
|---------------\routes
|-----------------------\apiRoutes.ts

Aqui dentro você encontra os método: /send
Partindo desse ponto, poderá criar o que deseja, visto que só replicar o que já tem disponível.

**Comment by mauropn** [comment]
Está disponível, nessa api, configurações de BOT, automatizada?  Vejo em alguns locais que fica dentro das filas, mas, na versão que eu baixei, não tem essas opções disponíveis. 
Gostaria de configurar gatilhos, como palavras chaves, por exemplo, para dispararem respostas automáticas específicas. Isso existe ou teria que ser programado ?


Obrigado!

**Comment by Kouthk** [comment]
Teria que ser programado.

**Comment by PwccaCode** [comment]
documentação encontrada issue resolvida
