### ISSUE TITLE
Problema na mudança do status de entrega com versões modificadas do Whatsapp(GbWhatsapp) e IOS

### ISSUE THREAD

**Issue by AdrianoRobson** [canove/whaticket-community#545]
Recentemente notei alguns problemas na atualização do status de envio com relação ao envio de mensagem para Whatsapps modificados como gbwhatsapp, yowhatsapp e etc alem de algumas versões de IOS.
Nesses casos, a mensagem é enviada com um delay de cerca de 2 secundos e na maioria das vezes, seu status de envio fica no relogio. Estou usando a versão do whatsapp-web.js mais recente: v1.20.0 mas esse problema ja vinha acontecendo em outras versões.

OS: Ubuntu 20.04
Node: v16.14.2

Abaixo há um print que exemplifica o envio de mensagem para whatsapp oficial e whatsapp modificado:
![2023-05-22_11-14](https://github.com/canove/whaticket-community/assets/40671414/034a99a6-49af-4396-82d4-42829ad1836d)
![2023-05-22_11-13](https://github.com/canove/whaticket-community/assets/40671414/d165ed69-b944-42c9-9068-9a8a05ce561d)

**Comment by PabloGuilherme** [comment]
Alguma solução?

**Comment by AdrianoRobson** [comment]
> Alguma solução?

Sim. Basta alterar o tempo de delay de 500ms para 4s no metodo handleMsgAck que esta no arquivo wbotMessageListener.ts

Antes:
```
const handleMsgAck = async (msg: WbotMessage, ack: MessageAck) => {
  await new Promise(r => setTimeout(r, 500));

  const io = getIO();
```

Depois:
```
const handleMsgAck = async (msg: WbotMessage, ack: MessageAck) => {
  await new Promise(r => setTimeout(r, 4000));

  const io = getIO();
```
