### ISSUE TITLE
Erro ao Executar comando

### ISSUE THREAD

**Issue by arpini10** [canove/whaticket-community#548]
Bom dia.
Sempre que vou executar o comando:
npx sequelize db:migrate

Apresenta o seguinte erro:
**Loaded configuration file "dist/config/database.js".

ERROR: Access denied for user 'whaticket'@'172.17.0.1' (using password: YES)**

Alguém poderia me auxiliar por favor?

**Comment by Gaguiar** [comment]
Bom dia!

Tive este mesmo problema, verifique se vc alterou a senha do projeto, acesso o banco de dados e confere se a senha do usuário whaticket está funcionando.

**Comment by Lord-Sajor** [comment]
Buenos dias,
Yo tuve el mismo problema, en ese momento lo estaba tratando de ejecutar con docker (yo realizaba la instalación en Windows). Lo solucione usando xampp (mysql). Yo creo que el problema será algún archivo de configuración relacionado con permisos desde la base de datos.

**Comment by Gaguiar** [comment]
> Buenos dias, Yo tuve el mismo problema, en ese momento lo estaba tratando de ejecutar con docker (yo realizaba la instalación en Windows). Lo solucione usando xampp (mysql). Yo creo que el problema será algún archivo de configuración relacionado con permisos desde la base de datos.

If you using docker you can try this:
Open terminal and execute , docker exec -it "DB INTANCE NAME" -u "db user previous created" -p, after you access your mysql db you need a grant permissions to your user like as, GRANT ALL PRIVILEGES ON "database_name".* TO "username"@'localhost';
