### ISSUE TITLE
Icone de status da mensagem não muda.

### ISSUE THREAD

**Issue by fernandodenardin** [canove/whaticket-community#549]
Olá pessoal estou passando pelo seguinte problema: Ao enviar uma mensagem o ícone da mensagem fica apenas o relóginho, não mudando para os tracinhos. Ao verificar no celular a mensagem é enviada normalmente. Alguém passando pelo mesmo problema?

**Comment by PwccaCode** [comment]
Sim, mas é apenas um problema visual se atualizar a pagina funciona normalmente, provavelmente algum problema relacionado ao socket
