### ISSUE TITLE
delay message

### ISSUE THREAD

**Issue by fahmimajd** [canove/whaticket-community#554]
help me, incoming messages are delayed for a very long time on WATICKET, its delay until 30min.

i using latest whatsap-web.js
"_id": "whatsapp-web.js@1.21.0",

this is from my phone
![image](https://github.com/canove/whaticket-community/assets/83627887/ee312904-936a-4be9-8b19-dc97b06adcde)

this is whaticket 
![image](https://github.com/canove/whaticket-community/assets/83627887/0796f9c1-e04d-478f-91c5-ef3b63d79245)

there is log
/home/deploy/.pm2/logs/whaticket-frontend-out.log last 15 lines:
/home/deploy/.pm2/logs/whaticket-frontend-error.log last 15 lines:
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'
1|whaticke | Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'

/home/deploy/.pm2/logs/whaticket-backend-error.log last 15 lines:
0|whaticke |     at navigate (/home/deploy/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)
0|whaticke |     at runMicrotasks (<anonymous>)
0|whaticke |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
0|whaticke |     at async FrameManager.navigateFrame (/home/deploy/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)
0|whaticke |     at async Frame.goto (/home/deploy/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)
0|whaticke |     at async Page.goto (/home/deploy/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
0|whaticke |     at async Client.initialize (/home/deploy/whaticket/backend/node_modules/whatsapp-web.js/src/Client.js:112:9)
0|whaticke | TypeError: data.id.id.substring is not a function
0|whaticke |     at Message._patch (/home/deploy/whaticket/backend/node_modules/whatsapp-web.js/src/structures/Message.js:91:75)
0|whaticke |     at new Message (/home/deploy/whaticket/backend/node_modules/whatsapp-web.js/src/structures/Message.js:18:24)
0|whaticke |     at /home/deploy/whaticket/backend/node_modules/whatsapp-web.js/src/structures/Chat.js:210:34
0|whaticke |     at Array.map (<anonymous>)
0|whaticke |     at PrivateChat.fetchMessages (/home/deploy/whaticket/backend/node_modules/whatsapp-web.js/src/structures/Chat.js:210:25)
0|whaticke |     at runMicrotasks (<anonymous>)
0|whaticke |     at processTicksAndRejections (internal/process/task_queues.js:95:5)

thanks for help

**Comment by jonathas-sh** [comment]
@fahmimajd 
Hello, were you able to solve this? If so, how did you do it?
