### ISSUE TITLE
CORS no localhost 

### ISSUE THREAD

**Issue by herbertamaro2** [canove/whaticket-community#555]
Olá grupo!!
Estou com um problema aqui fiz a instalação no ubuntu aqui backend frontend.. Mais quando vou rodar o frontend em localhost:3000 fica travado com 'erro de CORS'

obs: Quando faço login via postman funciona de boa o backend.
Já fiz de tudo aqui troquei as urls dos .envs umas dez mil vezes, estou 2 dias travado nesse CORS aee

#env frontend
`REACT_APP_BACKEND_URL = http://localhost:8080/`

#env backend
NODE_ENV=
BACKEND_URL=http://localhost
FRONTEND_URL=http://localhost:3000
PROXY_PORT=8080
PORT=8080

DB_HOST=localhost
DB_DIALECT=mysql
DB_USER=root
DB_PASS=
DB_NAME=whaticket

JWT_SECRET=3123123213123
JWT_REFRESH_SECRET=75756756756

**Comment by herbertamaro2** [comment]
Resolvi aqui galera, caso alguem precise só desativei o cors no backend como false credentials

`app.use(
  cors({
    credentials: false,
    origin: process.env.FRONTEND_URL
  })
);`

e no frontend em services/api.ts mudei withCredentials para false

`withCredentials: false`

**Lembrando isso é só configuração para localhost caso trave que nem o meu, em produção nunca façam isso**

**Comment by GabrielMaestre** [comment]
Como resolve isso em produção?
