### ISSUE TITLE
Problems trying to connect WhatsApp

### ISSUE THREAD

**Issue by cristopherybd** [canove/whaticket-community#570]
I updated ws-w-js to version 1.22.1, the QR is displayed correctly, but at the time of scanning it it does not connect, however in the whatsapp app an active session appears and then it disconnects.

I also have node version 14.21.3, any way to see what could be the problem or if there is a solution?

**Comment by luan-hubner** [comment]
exactly the same here, i already updated whatsapp-web.js to 1.22.1 too, but still dont connect

**Comment by liniglia** [comment]
caramba, estou o dia inteiro com isso também.
Ele conecta no celular, no log do PM2 - backend ele da como conectado só que fica travado no QRCode e se eu dou "esc" simplesmente desconecta (log) e não faz nada.

**Comment by liniglia** [comment]
será que alguma atualização do WhatsApp pode ter impactado o Whaticket?

**Comment by luan-hubner** [comment]
então, na issue #565 aparentemente resolveu o problema de conexão atualizando o wswebjs para a versão 1.22.1, mas para mim não foi suficiente, você tentou atualizar para ver se dá certo para você?

**Comment by luan-hubner** [comment]
consegui resolver o meu problema, após atualizar a lib wswebjs para a versão 1.22.1 alterei o código conforme está demonstrado na issue [https://github.com/pedroslopez/whatsapp-web.js/issues/2429] no arquivo src/Client.js.

reiniciei o serviço e a conexão já foi estabelecida normalmente.

**Comment by cristopherybd** [comment]
> luan-hubner

Excellent, I applied that change and it worked.

Thank you all.
