### ISSUE TITLE
Ticket retido na fila AGUARDANDO

### ISSUE THREAD

**Issue by compupack** [canove/whaticket-community#616]
Após testar a função de Campanhas, o ticket para um cliente ficou retido na fila "Aguardando" e não há os botões de aceitar nem de fechar o ticket, causando um bug.
Já tentei agendar mensagens, responder, nada funciona... Alguém tem alguma sugestão?

<img width="1429" alt="image" src="https://github.com/canove/whaticket-community/assets/157523797/1f13b2e1-4dec-432d-845d-bbdae8e23d43">

**Comment by allgood** [comment]
acredito que a versão do print não é a deste repositório.

**Comment by compupack** [comment]
Resolvi simplesmente deletando o contato em questão (o whaticket informa que todas as conversas com aquele contato serão perdidas). Fica a dica para alguém, caso passe pelo mesmo problema.. Abraços!

**Comment by Jolu54** [comment]
Você tem o código dessa versão do whaticket?
