### ISSUE TITLE
qr does not connect, it could be that whatsapp blocked the qr

### ISSUE THREAD

**Issue by CharlySoftCO** [canove/whaticket-community#629]
Good morning colleagues, yesterday I started to experience a connection problem with my QR codes in several systems that I have deployed.
![2024-04-04 06 44 33](https://github.com/canove/whaticket-community/assets/75139447/cffe1565-6b02-4a01-aced-1e9caaba3e1f)

**Comment by Gecko2087** [comment]
Good morning. I'm having the same problem since yesterday. Can someone help us with the solution? I saw that the WhatsApp Web JS library was not updated again.

**Comment by fabiodevn1** [comment]
Segue a solução

Remova o whatsappweb
npm uninstall whatsapp-web.js

Instale a versão corrigida
npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

**Comment by Gecko2087** [comment]
> Segue a solução
> 
> Remova o whatsappweb npm uninstall whatsapp-web.js
> 
> Instale a versão corrigida npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
Thank you so much! I had just found the same solution elsewhere.
I just tried it and it works.

In my case I had to add the following to make it work.

npm uninstall whatsapp-web.js
npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
npm install
pm2 restart all

**Comment by smorigo** [comment]
Pessoal fiz a instalação, faço a leitura do QRCode, olhei no log do browser e reparei que estou recebendo esse erro:

![image](https://github.com/canove/whaticket-community/assets/2990950/9b3ad82a-c57f-4ab9-81c2-3579490038c4)

Essa maquina está rodando na AWS, alguém tem alguma idea do que pode ser ?

**Comment by Flag-King** [comment]
> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

Aqui estou tendo o mesmo erro, porém esta solução aparentemente não funcionou ou eu não captei o que precisa fazer [rs].
Este comando roda no diretório raiz do Whaticket? Ou no Back / Frontend?

**Comment by Gecko2087** [comment]
Hello people. Now I'm having trouble adding a connection. It stays charging and doesn't show me to scan the QR code. Does anyone know how to solve it?

![image](https://github.com/canove/whaticket-community/assets/22262813/73d8e071-0032-4875-8c4d-8835bd54a9aa)

**Comment by rubensflinco** [comment]
> Segue a solução
> 
> Remova o whatsappweb npm uninstall whatsapp-web.js
> 
> Instale a versão corrigida npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

Mesmo eu faço esses passo ainda continuo tendo problemas, segue um print do erro que encontro no terminal do servidor apos escanear o QRCode: 
![image](https://github.com/canove/whaticket-community/assets/6248317/8752b075-6cc7-4dd6-a534-c4613b2e36d7)

Alguem pode me ajudar?

**Comment by LucasCCS** [comment]
> > Segue a solução
> > Remova o whatsappweb npm uninstall whatsapp-web.js
> > Instale a versão corrigida npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
> 
> Mesmo eu faço esses passo ainda continuo tendo problemas, segue um print do erro que encontro no terminal do servidor apos escanear o QRCode: ![image](https://private-user-images.githubusercontent.com/6248317/321724877-8752b075-6cc7-4dd6-a534-c4613b2e36d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NjgwMTksIm5iZiI6MTcxMjk2NzcxOSwicGF0aCI6Ii82MjQ4MzE3LzMyMTcyNDg3Ny04NzUyYjA3NS02Y2M3LTRkZDYtYTUzNC1jNDYxM2IyZTM2ZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTNUMDAyMTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTE2MjBjOGRkMmE4YTNkMGUyNDc0YzhiMjk2MWMzNjEzYjY5ODg2ZGMyNzJjNGIzOWQyOTk5OGUyZGRjYmRjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I11Njn-aCt6q6jIAVmjNFiX4SW-u5911-JJ21gp1IBc)
> 
> Alguem pode me ajudar?

/node_modules/whatsapp-web.js/src/Client.js - conteúdo interno da linha 695, aplicar validação nos window.Store?.Msg

` window.Store?.Msg.on('change', (msg) => { window.onChangeMessageEvent(window.WWebJS.getMessageModel(msg)); });
            window.Store?.Msg.on('change:type', (msg) => { window.onChangeMessageTypeEvent(window.WWebJS.getMessageModel(msg)); });
            window.Store?.Msg.on('change:ack', (msg, ack) => { window.onMessageAckEvent(window.WWebJS.getMessageModel(msg), ack); });
            window.Store?.Msg.on('change:isUnsentMedia', (msg, unsent) => { if (msg.id.fromMe && !unsent) window.onMessageMediaUploadedEvent(window.WWebJS.getMessageModel(msg)); });
            window.Store?.Msg.on('remove', (msg) => { if (msg.isNewMsg) window.onRemoveMessageEvent(window.WWebJS.getMessageModel(msg)); });
            window.Store?.Msg.on('change:body change:caption', (msg, newBody, prevBody) => { window.onEditMessageEvent(window.WWebJS.getMessageModel(msg), newBody, prevBody); });
            window.Store?.AppState.on('change:state', (_AppState, state) => { window.onAppStateChangedEvent(state); });
            window.Store?.Conn.on('change:battery', (state) => { window.onBatteryStateChangedEvent(state); });
            window.Store?.Call.on('add', (call) => { window.onIncomingCall(call); });
            window.Store?.Chat.on('remove', async (chat) => { window.onRemoveChatEvent(await window.WWebJS.getChatModel(chat)); });
            window.Store?.Chat.on('change:archive', async (chat, currState, prevState) => { window.onArchiveChatEvent(await window.WWebJS.getChatModel(chat), currState, prevState); });
            window.Store?.Msg.on('add', (msg) => {
                if (msg.isNewMsg) {
                    if(msg.type === 'ciphertext') {
                        // defer message event until ciphertext is resolved (type changed)
                        msg.once('change:type', (_msg) => window.onAddMessageEvent(window.WWebJS.getMessageModel(_msg)));
                        window.onAddMessageCiphertextEvent(window.WWebJS.getMessageModel(msg));
                    } else {
                        window.onAddMessageEvent(window.WWebJS.getMessageModel(msg));
                    }
                }
            });`

**Comment by LucasCCS** [comment]
> > Segue a solução
> > Remova o whatsappweb npm uninstall whatsapp-web.js
> > Instale a versão corrigida npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
> 
> Mesmo eu faço esses passo ainda continuo tendo problemas, segue um print do erro que encontro no terminal do servidor apos escanear o QRCode: ![image](https://private-user-images.githubusercontent.com/6248317/321724877-8752b075-6cc7-4dd6-a534-c4613b2e36d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NjU4NDksIm5iZiI6MTcxMjk2NTU0OSwicGF0aCI6Ii82MjQ4MzE3LzMyMTcyNDg3Ny04NzUyYjA3NS02Y2M3LTRkZDYtYTUzNC1jNDYxM2IyZTM2ZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMjM0NTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTZhZWQ3NmRhNzIwMTk5MzY3ZTM2ODI0MWJkMDlmYzk2Yjc2OTIxZGNkODQ1MTYwZTIzNzJjZjZiYmMxOGQ4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LV0AmLg7ahXPUaqCyU8Phn3C1wgBQGYRD28B44eOtZA)
> 
> Alguem pode me ajudar?

> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

Siga estes passos:

npm uninstall whatsapp-web.js
npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

Edite o arquivo src/libs/wbot.ts e acrescente no client:
`const wwebVersion = '2.2407.3';

webVersionCache: {
          type: 'remote',
          remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
        },
`

Deve ficar assim:
` const wwebVersion = '2.2407.3';

      const wbot: Session = new Client({
        session: sessionCfg,
        authStrategy: new LocalAuth({clientId: 'bd_'+whatsapp.id}),
        puppeteer: {
          executablePath: process.env.CHROME_BIN || undefined,
          // @ts-ignore
          browserWSEndpoint: process.env.CHROME_WS || undefined,
          args: args.split(' ')
        },
        webVersionCache: {
          type: 'remote',
          remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
        },
      });`

**Comment by CharlySoftCO** [comment]
campeon de bushi bol

**Comment by edilsonlsouza** [comment]
Olá! Durante toda a noite pesquisei sobre o erro e cada um tem uma gambiarra para colocar para funcionar, nessa nova versão não tem nada que faça funcionar. Isso deveria ser corrigido na fonte.

**Comment by lidernetworktecnologia** [comment]
mesma coisa aqui e ja tentei outras soluçoes sem sucesso...

**Comment by lidernetworktecnologia** [comment]
A dica do @LucasCCS  deu certo para mim, porem para que funcione nao usei o npm install, alterei diretamente o arquivo package.json com a versao correta ficando:  "whatsapp-web.js": "^1.23.1-alpha.5" 
depois removi o diretorio node_modules e fiz o install, apos isso alterei o arquivo src/libs/wbot.ts conforme abaixo:

const wwebVersion = '2.2407.3';
const wbot: Session = new Client({
    session: sessionCfg,
    authStrategy: new LocalAuth({clientId: 'bd_'+whatsapp.id}),
    puppeteer: {
      executablePath: process.env.CHROME_BIN || undefined,
      // @ts-ignore
      browserWSEndpoint: process.env.CHROME_WS || undefined,
      args: args.split(' ')
    },
webVersionCache: {
      type: 'remote',
      remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
    },
  });

**Comment by thigas88** [comment]
> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

@lidernetworktecnologia mesmo seguindo a dica do @LucasCCS e a sua adaptação ainda continuo tendo erros para registrar o número. Estou rodando em ambiente local em docker

```
2024-05-01 13:08:52 [1714579732709] ERROR: {"name":"JsonWebTokenError","message":"jwt malformed"}
2024-05-01 13:09:03 [1714579743010] INFO: Client Connected
2024-05-01 13:09:03 [1714579743077] INFO: Client Connected
2024-05-01 13:09:03 [1714579743086] INFO: Client Connected
2024-05-01 13:09:03 [1714579743273] INFO: Client Connected
2024-05-01 13:09:03 [1714579743276] INFO: Client Connected
2024-05-01 13:09:03 [1714579743276] INFO: A client joined to pending tickets channel.
2024-05-01 13:09:03 [1714579743277] INFO: Client Connected
2024-05-01 13:09:03 [1714579743278] INFO: A client joined to open tickets channel.
2024-05-01 13:09:03 [1714579743280] INFO: A client joined notification channel
2024-05-01 13:09:07 [1714579747348] INFO: Client disconnected
2024-05-01 13:09:07 [1714579747349] INFO: Client disconnected
2024-05-01 13:09:11 [1714579751074] INFO: Client Connected
2024-05-01 13:09:33 [1714579773390] INFO: Client disconnected
2024-05-01 13:09:49 (node:37) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
2024-05-01 13:09:49     at LocalWebCache.persist (/usr/src/app/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
2024-05-01 13:09:49     at /usr/src/app/node_modules/whatsapp-web.js/src/Client.js:744:36
2024-05-01 13:09:49     at runMicrotasks (<anonymous>)
2024-05-01 13:09:49     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2024-05-01 13:09:49 (node:37) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
```
*Tentativa 1*
- apaguei a pasta node_modules
- atualizei o package.json:  "whatsapp-web.js": "^1.23.1-alpha.5"
- npm install && npm run build

*Tentativa 2*
- apaguei a pasta node_modules
- atualizei o package.json:  "whatsapp-web.js": "github:pedroslopez/whatsapp-web.js#webpack-exodus"
- npm install && npm run build

Em ambas as tentativas  alterei o arquivo src/libs/wbot.ts.

Alguma outra ação para essa questão?

**Comment by lidernetworktecnologia** [comment]
@thigas88 mostra como esta seu arquivo wbot.ts?

**Comment by emanuelserpa** [comment]
Também estou fazendo o processo e nada funciona. :(

![image](https://github.com/canove/whaticket-community/assets/934124/e5770fad-025e-43bc-87b2-7ffd4280da64)

**Comment by lidernetworktecnologia** [comment]
Agora caiu denovo hoje e nao voltou mais mesmo com essas correçoes, esta dificil manter o Whaticket de uns tempos...

**Comment by rogeriosims** [comment]
Estou com mesmo problema.

**Comment by rogeriosims** [comment]
funcionou para mim
pm2 stop all
npm remove github:pedroslopez/whatsapp-web.js
npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

/home/rogerio/whaticket/backend/src/libs/wbot.ts

      const args:String = process.env.CHROME_ARGS || "";	  
	  const wwwebVersion = '2.2407.3';

      const wbot: Session = new Client({
        session: sessionCfg,
        authStrategy: new LocalAuth({clientId: 'bd_'+whatsapp.id}),
        puppeteer: {
		  headless: true , 
		  args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
			],
          executablePath: process.env.CHROME_BIN || undefined,
          // @ts-ignore
          browserWSEndpoint: process.env.CHROME_WS || undefined,
        },
		webVersionCache: {
		type: 'remote',
		remotePath: "https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwwebVersion}.html",
		},		
      });

**Comment by lidernetworktecnologia** [comment]
Deu certo aqui tambem com esta correçao, muito obrigado!

**Comment by jhozrabelo** [comment]
> funcionou para mim pm2 stop all npm remove github:pedroslopez/whatsapp-web.js npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
> 
> /home/rogerio/whaticket/backend/src/libs/wbot.ts
> 
> ```
>   const args:String = process.env.CHROME_ARGS || "";	  
>   const wwwebVersion = '2.2407.3';
> 
>   const wbot: Session = new Client({
>     session: sessionCfg,
>     authStrategy: new LocalAuth({clientId: 'bd_'+whatsapp.id}),
>     puppeteer: {
> 	  headless: true , 
> 	  args: [
>         '--no-sandbox',
>         '--disable-setuid-sandbox',
> 		],
>       executablePath: process.env.CHROME_BIN || undefined,
>       // @ts-ignore
>       browserWSEndpoint: process.env.CHROME_WS || undefined,
>     },
> 	webVersionCache: {
> 	type: 'remote',
> 	remotePath: "https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwwebVersion}.html",
> 	},		
>   });
> ```

tentei aqui mas não entendi esse ultimo processo das pastas, aqui ainda não deu certo

**Comment by jhozrabelo** [comment]
> Deu certo aqui tambem com esta correçao, muito obrigado!

como resolveu mano?

**Comment by fabiodevn1** [comment]
> > Deu certo aqui tambem com esta correçao, muito obrigado!
> 
> como resolveu mano?

Onde você chama o wbot você adiciona essas configurações, hoje uso a 2.2412 porém é a mesma configuração,

**Comment by jhozrabelo** [comment]
> > > Deu certo aqui tambem com esta correçao, muito obrigado!
> > 
> > 
> > como resolveu mano?
> 
> Onde você chama o wbot você adiciona essas configurações, hoje uso a 2.2412 porém é a mesma configuração,

nada de resolver adicionando nesse wbot

**Comment by rogeriosims** [comment]
> > > > Deu certo aqui tambem com esta correçao, muito obrigado!
> > > 
> > > 
> > > como resolveu mano?
> > 
> > 
> > Onde você chama o wbot você adiciona essas configurações, hoje uso a 2.2412 porém é a mesma configuração,
> 
> nada de resolver adicionando nesse wbot

Cara, passa mais informações do que você fez.

Não tem erro só seguir os passos:

1 - Para os serviços: pm2 stop all npm 
2 - Remover o whatsappJS 
       remove github:pedroslopez/whatsapp-web.js 
3 - Instalar a nova verrsão:
      npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
4 - Alterar a função no arquivo:
/home/rogerio/whaticket/backend/src/libs/wbot.ts

**Comment by hildors** [comment]
Prezados, ontem instalei o whaticket no aapanel ...  loguei certinho, porém quando vou adicionar um whatsapp, ele não carrega o modal do qrcode.  O status fica girando a sessão "conectando" e nada. Já segui os passos acima por duas vezes e não resolve.
Alguma dica do que pode ser?
Quando inspeciono os erros no navegador me aparece: 
WebSocket connection to wss://atendimento.dominio.com.br/socket.io/?token=2222222222  failed: WebSocket closed before  the connection is established .

Alguém tem alguma dica valiosa para fazer isso funcionar?

**Comment by CharlySoftCO** [comment]
Solution

npm uninstall whatsapp-web.js
npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
npm run build
pm2 restart all
