### ISSUE TITLE
QR Error never connects

### ISSUE THREAD

**Issue by AlejandroDevelopment** [canove/whaticket-community#643]
I installed whaticket as indicated in the installation guide, everything worked correctly but for a few days the QR no longer connects even though I have reinstalled whaticket multiple times.
This solution used to work for me before but not anymore. https://github.com/canove/whaticket-community/issues/638
Does anyone have the same issue? How can i solve it?

**Comment by guilhermefvaz** [comment]
I've been having the same problem for a few days now, but I haven't found a solution anywhere.
If you find something let me know here, if you can do the same if you find a solution.

**Comment by AlejandroDevelopment** [comment]
Did you got some solution? I will post the solution here if i solve it

**Comment by lu4nrc** [comment]
Alguem conseguiu resolver?

**Comment by AlejandroDevelopment** [comment]
Not yet

**Comment by lu4nrc** [comment]
I noticed that messages arrive if I put wbot.on("message_create", async (msg) => {
          console.log("wbot.js -> MESSAGE RECEIVED", {
            to: msg.to,
            body: msg.body,
          })}); the messages are arriving but there is some treatment that prevents them from being saved

**Comment by AlejandroDevelopment** [comment]
Can you sync whatsapp with QR code?

**Comment by lu4nrc** [comment]
You are using "whatsapp-web.js": "pedroslopez/whatsapp-web.js.git#webpack-exodus"?
It works well for some numbers.

**Comment by AlejandroDevelopment** [comment]
It just worked, i did a reinstallation and ran de following commands at the backend installation
-npm install
-npm uninstall whatsapp-web.js
-npm install pedroslopez/whatsapp-web.js.git#webpack-exodus --save
-npm uninstall @types/lodash
-npm install @types/lodash@4.17.5
-npm run build
(rest of installation...)
It works for me

**Comment by guilhermefvaz** [comment]
wow, thanks Alejandro.
