### ISSUE TITLE
qr does not connect,

### ISSUE THREAD

**Issue by grservices-uy** [canove/whaticket-community#648]
hi, 

i have install whaticket in vps ubuntu 20.04

I hope you can help me, when I connect the QR with the WhatsApp cell phone app, the cell phone has an active session but in Whaticket the connection status does not change

**Comment by AlejandroDevelopment** [comment]
Hey hello, you already tried this? https://github.com/canove/whaticket-community/issues/643#issuecomment-2234014586
i use ubuntu-20.04.6-live-server and it works

**Comment by grservices-uy** [comment]
Rally i now try it and its work!!!!  thank you!!
