### ISSUE TITLE
Sent messages do not appear

### ISSUE THREAD

**Issue by CharlySoftCO** [canove/whaticket-community#656]
![2024-09-03 14 07 07](https://github.com/user-attachments/assets/22574b0a-e26d-4fe9-a994-093befc97661)
Good afternoon colleagues, how are you? The following is happening to me: the messages sent do not appear in the chat

**Comment by valloo-daniel** [comment]
Same to me

**Comment by dudabastos82** [comment]
me too.

**Comment by CharlySoftCO** [comment]
Frontend permissions solution sudo chown www-data:www-data -R
