### ISSUE TITLE
Install on mesmo VPS

### ISSUE THREAD

**Issue by acortizoc** [canove/whaticket-community#671]
Puede ser instalado Backend y frontend en el mismo VPS?

He creado dos Nombres de dominio backend.flybit.es y frontend.flybit.es y los he puesto al inicio de la instalación pero cuando abro https://frontend.flybit.es/ recibo error
http://frontend.flybit.es/ recibo error
http//frontend.flybit.es:3333 recibo cors error
https//frontend.flybit.es:3333 cannot get /

Hay alguna limitacion o restricción de node, npm, ubuntu version u otras?

Alguna sugerencia?
Gracias

**Comment by grservices-uy** [comment]
Hola, se suoone que deben ir los dos en el mismo servidor sea vps o dedicado, que error recibe exactamente?

**Comment by acortizoc** [comment]
Recibo esto

![image](https://github.com/user-attachments/assets/39cf3a77-a50a-47e6-9740-49709757b92e)
